INSERT INTO HOUSEHOLDS (NAME) VALUES ('Smith Household');
INSERT INTO HOUSEHOLDS (NAME) VALUES ('Jones Household');

-- Password is 'password' BCrypt encoded
INSERT INTO USERS (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, HOUSEHOLD_ID)
VALUES ('john.smith@example.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'John', 'Smith', 1);

INSERT INTO USERS (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, HOUSEHOLD_ID)
VALUES ('jane.jones@example.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Jane', 'Jones', 2);

INSERT INTO ITEMS (ITEM_NAME, HOUSEHOLD_ID) VALUES ('Stand', 1);
INSERT INTO ITEMS (ITEM_NAME, HOUSEHOLD_ID) VALUES ('Saviets', 1);
INSERT INTO ITEMS (ITEM_NAME, HOUSEHOLD_ID) VALUES ('Toaster', 2);
INSERT INTO ITEMS (ITEM_NAME, HOUSEHOLD_ID) VALUES ('Salad Bowls', 2);
