DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS HOUSEHOLDS;

CREATE TABLE HOUSEHOLDS
(
    HOUSEHOLD_ID BIGINT       NOT NULL AUTO_INCREMENT,
    NAME         VARCHAR(255) NOT NULL,
    PRIMARY KEY (HOUSEHOLD_ID)
);

CREATE TABLE USERS
(
    USER_ID      BIGINT       NOT NULL AUTO_INCREMENT,
    EMAIL        VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD     VARCHAR(255) NOT NULL,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    HOUSEHOLD_ID BIGINT,
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (HOUSEHOLD_ID) REFERENCES HOUSEHOLDS (HOUSEHOLD_ID)
);

CREATE TABLE ITEMS
(
    ITEM_ID      BIGINT       NOT NULL AUTO_INCREMENT,
    ITEM_NAME    VARCHAR(255) NOT NULL,
    HOUSEHOLD_ID BIGINT       NOT NULL,
    PRIMARY KEY (ITEM_ID),
    FOREIGN KEY (HOUSEHOLD_ID) REFERENCES HOUSEHOLDS (HOUSEHOLD_ID)
);
