DROP TABLE IF EXISTS ITEMS;

CREATE TABLE ITEMS
(
    ITEM_ID   INTEGER      NOT NULL,
    ITEM_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ITEM_ID)
);

INSERT INTO ITEMS (ITEM_ID, ITEM_NAME)
VALUES (1, 'Stand');
INSERT INTO ITEMS (ITEM_ID, ITEM_NAME)
VALUES (2, 'Saviets');
INSERT INTO ITEMS (ITEM_ID, ITEM_NAME)
VALUES (3, 'Toaster');
INSERT INTO ITEMS (ITEM_ID, ITEM_NAME)
VALUES (4, 'Salad Bowls');
